name = "post-purchase-offer"
uid = "6752028e-ec43-8393-87c7-8d22c1de0b5c0782eb8d"
type = "checkout_post_purchase"
api_version = "2026-01"

[[extension_points]]
target = "Checkout::PostPurchase::ShouldRender"
module = "./src/index.js"

[[extension_points]]
target = "Checkout::PostPurchase::Render"
module = "./src/index.js"
